---
version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout: {}
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          command: |
            make html
      - persist_to_workspace:
          root: .
          paths:
            - ./build/html/
            - ./deploy/
  deploy:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - run:
          name: Install rsync
          command: |
            sudo apt-get update
            sudo apt-get install --assume-yes rsync
      - add_ssh_keys:
          fingerprints:
            - 4d:f4:46:2f:69:ee:a0:bd:9c:29:fe:de:18:00:f1:de
      - run:
          name: Install a key to known_hosts
          command: |
            mkdir -p ~/.ssh
            cat \<< EOF >> ~/.ssh/known_hosts
            [s9.rs2plus.gehirn.ne.jp]:22311,[153.127.109.65]:22311 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGh08oN+BTakK+pFUgZPI9lj1mb8vSuNtl7RmTf/KUmoNYeI/y54HvNMHaWNuy4/Zco3zFctBkZIk4FxPFrVDR4=
            EOF
      - attach_workspace:
          at: .
      - run:
          name: Deploy to the stage environment
          command: |
            ./deploy/production.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build: {}
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
